// Generates app version artifacts before build/start
// - public/app-version.json (served to clients)
// - src/version.ts (embedded in the bundle for self-version)

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

function getGitCommitShort(): string | null {
    try {
        const output = execSync('git rev-parse --short HEAD', {
            stdio: ['ignore', 'pipe', 'ignore'],
            encoding: 'utf8',
        })
            .toString()
            .trim();
        return output || null;
    } catch (e) {
        return null;
    }
}

function ensureDirSync(targetDir: string): void {
    if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
    }
}

interface VersionPayload {
    version: string;
    commit?: string | null;
    buildTime: string;
    buildId: string;
}

function main(): void {
    const root = __dirname ? path.resolve(__dirname, '../..') : process.cwd();
    const pkgPath = path.join(root, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8')) as { version?: string };

    const version = pkg.version || '0.0.0';
    const commit = getGitCommitShort();
    const buildTime = new Date().toISOString();
    const buildId = `${version}-${commit || 'local'}-${Date.now()}`;

    const payload: VersionPayload = {
        version,
        commit: commit || undefined,
        buildTime,
        buildId,
    };

    // Write public/app-version.json (consumed at runtime via fetch)
    const publicDir = path.join(root, 'public');
    ensureDirSync(publicDir);
    const versionJsonPath = path.join(publicDir, 'app-version.json');
    fs.writeFileSync(versionJsonPath, JSON.stringify(payload, null, 2), 'utf8');

    // Write src/version.ts (embedded in the bundle)
    const srcDir = path.join(root, 'src');
    ensureDirSync(srcDir);
    const versionTsPath = path.join(srcDir, 'version.ts');
    const tsContent =
        `// Auto-generated by scripts/generate-version.ts\n` +
        `export const CURRENT_VERSION = ${JSON.stringify(version)};\n` +
        `export const CURRENT_BUILD_ID = ${JSON.stringify(buildId)};\n` +
        `export const CURRENT_COMMIT = ${JSON.stringify(commit)};\n` +
        `export const CURRENT_BUILD_TIME = ${JSON.stringify(buildTime)};\n`;
    fs.writeFileSync(versionTsPath, tsContent, 'utf8');

    // eslint-disable-next-line no-console
    console.log('[version] Generated:', { version, commit, buildId });
}

main();
