/**
 * Main build wrapper - Orchestrates version generation and build process
 */

import * as path from 'path';
import * as fs from 'fs';
import { readConfig } from '../utils/config-reader';
import { Logger } from '../utils/logger';
import { ReactScriptsAdapter } from './adapters/react-scripts';
import { ViteAdapter } from './adapters/vite';
import { WebpackAdapter } from './adapters/webpack';
import { BuildAdapter } from './adapters/base';
import { VERSION_FILE_NAME } from '../constants/defaults';
import { AppVersion } from '../types/config';

const logger = new Logger();

/**
 * Get the appropriate adapter based on config
 */
function getAdapter(adapterName: string): BuildAdapter {
  switch (adapterName) {
    case 'react-scripts':
      return new ReactScriptsAdapter();
    case 'vite':
      return new ViteAdapter();
    case 'webpack':
      return new WebpackAdapter();
    default:
      throw new Error(`Unknown adapter: ${adapterName}`);
  }
}

/**
 * Generate a simple build hash
 */
function generateBuildId(): string {
  return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
}

/**
 * Get package version from package.json
 */
function getPackageVersion(): string {
  try {
    const packageJsonPath = path.join(process.cwd(), 'package.json');
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
    return packageJson.version || '0.0.0';
  } catch (error) {
    logger.warn('Could not read package.json version, using 0.0.0');
    return '0.0.0';
  }
}

/**
 * Write version.ts to src directory
 */
function writeSourceVersionFile(versionData: AppVersion): void {
  const srcDir = path.join(process.cwd(), 'src');
  const versionFilePath = path.join(srcDir, 'version.ts');

  if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir, { recursive: true });
  }

  const fileContent = `// Auto-generated by react-zero-downtime-build
export const CURRENT_VERSION = '${versionData.version}';
export const CURRENT_BUILD_ID = '${versionData.buildId}';
export const CURRENT_COMMIT = null;
export const CURRENT_BUILD_TIME = '${new Date(versionData.timestamp).toISOString()}';
`;

  fs.writeFileSync(versionFilePath, fileContent, 'utf-8');
  logger.success(`Updated source version file: ${versionFilePath}`);
}

/**
 * Generate version file in output directory
 */
function generateVersionFile(outputDir: string, versionData: AppVersion): void {
  const versionFilePath = path.join(outputDir, VERSION_FILE_NAME);

  // Ensure output directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(
    versionFilePath,
    JSON.stringify(versionData, null, 2),
    'utf-8'
  );

  logger.success(`Generated output version file: ${versionFilePath}`);
  logger.info(`Version: ${versionData.version}, Build ID: ${versionData.buildId}`);
}

/**
 * Main build wrapper function
 */
export async function buildWrapper(): Promise<void> {
  try {
    logger.log('🚀 React Zero Downtime Build - Starting...');

    // Read configuration
    const config = readConfig();
    logger.info('Configuration loaded:', config);

    // Get the appropriate adapter
    const adapter = getAdapter(config.adapter);

    // Validate the adapter
    if (!adapter.validate()) {
      throw new Error(
        `${adapter.name} adapter validation failed. ` +
        `Make sure ${adapter.name} is installed in your project.`
      );
    }

    logger.log(`Using ${adapter.name} adapter`);

    // Prepare version data
    const packageVersion = getPackageVersion();
    const buildId = generateBuildId();
    const versionData: AppVersion = {
      version: packageVersion,
      timestamp: Date.now(),
      buildId: buildId,
    };

    // 1. Write src/version.ts BEFORE build so it gets bundled
    logger.log('Updating source version...');
    writeSourceVersionFile(versionData);

    // 2. Execute the build
    logger.log('Building application...');
    const outputDir = adapter.getOutputDir(config);
    await adapter.build(config);
    logger.success('Build completed successfully!');

    // 3. Generate version file in the output directory AFTER build
    generateVersionFile(outputDir, versionData);

    logger.success('✅ React Zero Downtime Build - Complete!');
  } catch (error) {
    logger.error('Build failed:', error);
    process.exit(1);
  }
}

// Run if executed directly
if (require.main === module) {
  buildWrapper();
}
