// Auto-generated by scripts/generate-version.ts
export const CURRENT_VERSION = '0.1.0';
export const CURRENT_BUILD_ID = '0.1.0-local-1733388000000';
export const CURRENT_COMMIT = null;
export const CURRENT_BUILD_TIME = new Date().toISOString();
